# Limpa e compila o site

all: build

build: clean install
	@echo ""; \
	       	echo "run \"npm start\" now, Have a nice day :)"

install:
	npm install

update:
	npm update

clean: 
	rm -rf node_modules
